name: yelp_task
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  retrofit: '>=4.0.0 <5.0.0'
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.3.1

  dio: any
  flutter_rating_stars: ^1.1.0
  url_launcher: ^6.3.0
  flutter_linkify: ^6.0.0
  link_text: ^0.2.1
  cached_network_image: ^3.3.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: '>=5.0.0 <6.0.0'
  build_runner: '>2.3.0 <4.0.0'
  json_serializable: ^6.8.0
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
